batch_size: 128
log_every: 20
max_sen_length: 100
mixed_precision_trainig: true
model_name: LOANT
optimize_bert: false
optimize_cls_repr: true
pretrained_model: bert
sample_selection: false
task_pretrained: false
task_pretrained_weights: null
training_epochs: 5
